apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-infra-db-pvc
  namespace: test-infrastructure-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
