route:
  receiver: 'default'
  group_by: ['alertname','service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - severity="critical"
      receiver: 'critical'
      continue: true
    - matchers:
        - service="performance_monitor"
      receiver: 'ops'
      group_wait: 15s

inhibit_rules:
  - source_matchers: [ severity="critical" ]
    target_matchers: [ severity="warning" ]
    equal: ['alertname','service']

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://technical-service-assistant:3000/api/alerts/mock'
        send_resolved: true
  - name: 'critical'
    webhook_configs:
      - url: 'http://technical-service-assistant:3000/api/alerts/critical'
        send_resolved: true
  - name: 'ops'
    webhook_configs:
      - url: 'http://technical-service-assistant:3000/api/alerts/ops'
        send_resolved: true
  # Example email receiver (disabled until SMTP configured)
  # - name: 'email'
  #   email_configs:
  #     - to: 'alerts@example.com'
  #       from: 'noreply@example.com'
  #       smarthost: 'smtp:25'
  #       require_tls: false

templates: []
