apiVersion: 1

datasources:
  - name: Alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    uid: alertmanager
    url: http://alertmanager:9093
    isDefault: false
    editable: false
    jsonData:
      implementation: prometheus
