name: Docs Quality

on:
  pull_request:
    paths:
      - '**.md'
      - '.github/workflows/docs-check.yml'
  push:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Install markdownlint
        run: npm install -g markdownlint-cli@0.39.0

      - name: Lint Markdown
        run: |
          markdownlint '**/*.md' || (echo '::warning ::Markdown lint found issues' && exit 1)

  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install lychee (link checker)
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,206,429
            --exclude-mail
            --timeout 20
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
