name: Python Tests

on:
  pull_request:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - '.github/workflows/tests.yml'
      - 'tests/**'
      - 'scripts/eval_suite.py'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests with coverage
        run: |
          pytest -q --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=60
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
